import Foundation

/// Generates the JavaScript source code for the Logic Pro Scripter MIDI FX bridge.
///
/// This script runs inside Logic Pro's Scripter plugin and acts as a bidirectional
/// communication bridge between the MCP server (via MIDI CC/SysEx) and Logic Pro's
/// internal scripting APIs (GetTimingInfo, ProcessMIDI, HandleMIDI).
///
/// The script is generated at runtime so it can embed protocol constants
/// from `ScripterProtocol` rather than duplicating magic numbers.
public enum BridgeScript {

    /// Generate the complete JavaScript source for the Scripter bridge plugin.
    public static func generate() -> String {
        """
        // Logic Pro MCP Bridge — Scripter MIDI FX Plugin
        // Generated by logic-pro-mcp. Do not edit manually.
        //
        // Protocol: receives CC commands on channel 16, responds with SysEx.
        // CC \(ScripterProtocol.commandCC) = command dispatch
        // CC \(ScripterProtocol.paramCC1) = parameter 1
        // CC \(ScripterProtocol.paramCC2) = parameter 2

        var NeedsTimingInfo = true;

        // SysEx prefix: F0 00 7E 4C
        var SYSEX_PREFIX = [0xF0, 0x00, 0x7E, 0x4C];
        var SYSEX_END = 0xF7;
        var CMD_CHANNEL = \(ScripterProtocol.midiChannel); // 0-indexed channel 16
        var CMD_CC = \(ScripterProtocol.commandCC);
        var PARAM_CC1 = \(ScripterProtocol.paramCC1);
        var PARAM_CC2 = \(ScripterProtocol.paramCC2);

        // Command IDs (must match ScripterCommand in Swift)
        var CMD_PING = 1;
        var CMD_GET_TIMING = 2;
        var CMD_START_CAPTURE = 3;
        var CMD_STOP_CAPTURE = 4;
        var CMD_GET_VERSION = 5;

        // Response types (must match ScripterResponseType in Swift)
        var RSP_PONG = 1;
        var RSP_TIMING = 2;
        var RSP_NOTES = 3;
        var RSP_VERSION = 5;
        var RSP_ERROR = 127;

        // State
        var paramByte1 = 0;
        var paramByte2 = 0;
        var isCapturing = false;
        var capturedNotes = [];

        function HandleMIDI(event) {
            // Only intercept CC on the bridge channel
            if (event instanceof ControlChange && event.channel == CMD_CHANNEL + 1) {
                if (event.number == PARAM_CC1) {
                    paramByte1 = event.value;
                    return; // consume
                }
                if (event.number == PARAM_CC2) {
                    paramByte2 = event.value;
                    return; // consume
                }
                if (event.number == CMD_CC) {
                    handleCommand(event.value);
                    return; // consume
                }
            }

            // Capture notes if active
            if (isCapturing && event instanceof Note) {
                var info = GetTimingInfo();
                capturedNotes.push({
                    pitch: event.pitch,
                    velocity: event.velocity,
                    beat: info ? info.blockStartBeat : 0,
                    type: (event.velocity > 0) ? "on" : "off"
                });
            }

            // Pass through all non-bridge MIDI
            event.send();
        }

        function handleCommand(cmdId) {
            switch (cmdId) {
                case CMD_PING:
                    sendResponse(RSP_PONG, "{}");
                    break;
                case CMD_GET_TIMING:
                    sendTimingInfo();
                    break;
                case CMD_START_CAPTURE:
                    isCapturing = true;
                    capturedNotes = [];
                    break;
                case CMD_STOP_CAPTURE:
                    isCapturing = false;
                    sendResponse(RSP_NOTES, JSON.stringify(capturedNotes));
                    capturedNotes = [];
                    break;
                case CMD_GET_VERSION:
                    sendResponse(RSP_VERSION, JSON.stringify({
                        version: "0.1.0",
                        protocol: 1,
                        capabilities: ["timing", "noteCapture"]
                    }));
                    break;
                default:
                    sendResponse(RSP_ERROR, JSON.stringify({
                        error: "unknown command",
                        cmdId: cmdId
                    }));
            }
            // Reset params after command execution
            paramByte1 = 0;
            paramByte2 = 0;
        }

        function sendTimingInfo() {
            var info = GetTimingInfo();
            if (!info) {
                sendResponse(RSP_ERROR, JSON.stringify({error: "no timing info"}));
                return;
            }
            var data = {
                tempo: info.tempo,
                meterNumerator: info.meterNumerator,
                meterDenominator: info.meterDenominator,
                blockStartBeat: info.blockStartBeat,
                blockEndBeat: info.blockEndBeat,
                blockLength: info.blockLength,
                isPlaying: info.playing,
                isCycling: info.cycling,
                leftCycleBeat: info.leftCycleBeat,
                rightCycleBeat: info.rightCycleBeat
            };
            sendResponse(RSP_TIMING, JSON.stringify(data));
        }

        // Encode a JSON string as 7-bit safe SysEx and send it.
        // Every 7 input bytes become 8 output bytes (1 high-bit header + 7 masked bytes).
        function sendResponse(responseType, jsonString) {
            var raw = [];
            for (var i = 0; i < jsonString.length; i++) {
                raw.push(jsonString.charCodeAt(i));
            }

            var encoded = encode7Bit(raw);
            var sysex = new Sysex();
            // Build data array (everything between F0 and F7, exclusive)
            var data = [0x00, 0x7E, 0x4C, responseType];
            for (var j = 0; j < encoded.length; j++) {
                data.push(encoded[j]);
            }
            sysex.data = data;
            sysex.send();
        }

        function encode7Bit(data) {
            var output = [];
            var i = 0;
            while (i < data.length) {
                var chunkEnd = Math.min(i + 7, data.length);
                var highBits = 0;
                for (var b = i; b < chunkEnd; b++) {
                    if (data[b] & 0x80) {
                        highBits |= (1 << (b - i));
                    }
                }
                output.push(highBits);
                for (var c = i; c < chunkEnd; c++) {
                    output.push(data[c] & 0x7F);
                }
                i = chunkEnd;
            }
            return output;
        }
        """
    }
}
